# Generated by Django 6.0.6 on 2026-07-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('credential_id', models.CharField(blank=True, max_length=200)),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/pdf/')),
                ('verification_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
    ]
