# Generated by Django 6.0.6 on 2026-07-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='certificates/pdf/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='certificates/'),
        ),
    ]
