# Generated by Django 6.0.6 on 2026-07-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Languages', 'Languages'), ('Frameworks', 'Frameworks'), ('Tools & Technologies', 'Tools & Technologies')], max_length=50),
        ),
    ]
